# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required Container Registry settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - docker_registry_hostname
    - docker_registry_uid
    - docker_registry_gid

- name: Fail if required Container Registry whitelisted IP ranges not defined
  ansible.builtin.fail:
    msg: >-
      You need to define at least one IP range in `docker_registry_private_services_whitelisted_ip_ranges` for using this role.
  when: docker_registry_private_services_whitelisted_ip_ranges | length == 0

- name: Fail if required Container Registry + Traefik integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `docker_registry_container_labels_traefik_enabled`
  when: "docker_registry_container_labels_traefik_enabled | bool and vars[item] == ''"
  with_items:
    - docker_registry_container_labels_traefik_docker_network
